Repository urho3d/urho3d, pull requests merged in 2019-08, with the labels that each got.

#2468 Tooltip improvements
  Source/Urho3D/AngelScript/UIAPI.cpp
  Source/Urho3D/LuaScript/pkgs/UI/ToolTip.pkg
  Source/Urho3D/UI/ToolTip.cpp
  Source/Urho3D/UI/ToolTip.h
Labels: enhancement

#2485 Fixed the depth test behavior of debug renderer sphere sectors.
  Source/Urho3D/Graphics/DebugRenderer.cpp
  Source/Urho3D/Graphics/DebugRenderer.h
Labels: bug

#2476 More custom geometry
  Source/Urho3D/Container/Vector.h
  Source/Urho3D/Graphics/CustomGeometry.cpp
  Source/Urho3D/Graphics/CustomGeometry.h
  Source/Urho3D/Math/MathDefs.h
  Source/Urho3D/Math/Matrix3.cpp
  Source/Urho3D/Math/Matrix3.h
  Source/Urho3D/Math/Vector3.h
Labels: enhancement

#2492 Make doxygen catch global enums
  Source/Urho3D/AngelScript/Script.h
  Source/Urho3D/AngelScript/ScriptInstance.h
  Source/Urho3D/Core/Attribute.h
  Source/Urho3D/Core/Spline.h
  Source/Urho3D/Core/Variant.h
  Source/Urho3D/Database/Database.h
  Source/Urho3D/Graphics/Animation.h
  Source/Urho3D/Graphics/AnimationState.h
  Source/Urho3D/Graphics/Camera.h
  Source/Urho3D/Graphics/Drawable.h
  Source/Urho3D/Graphics/GraphicsDefs.h
  Source/Urho3D/Graphics/Light.h
  Source/Urho3D/Graphics/OcclusionBuffer.h
  Source/Urho3D/Graphics/OctreeQuery.h
  Source/Urho3D/Graphics/ParticleEffect.h
  Source/Urho3D/Graphics/RenderPath.h
  Source/Urho3D/Graphics/Renderer.h
  Source/Urho3D/Graphics/RibbonTrail.h
  Source/Urho3D/Graphics/Skeleton.h
  Source/Urho3D/Graphics/Technique.h
  Source/Urho3D/IO/File.h
  Source/Urho3D/Input/Input.h
  Source/Urho3D/Input/InputConstants.h
  Source/Urho3D/LuaScript/LuaScriptInstance.h
  Source/Urho3D/Math/Frustum.h
  Source/Urho3D/Math/MathDefs.h
  Source/Urho3D/Navigation/CrowdAgent.h
  Source/Urho3D/Navigation/NavigationMesh.h
  Source/Urho3D/Network/Connection.h
  Source/Urho3D/Network/HttpRequest.h
  Source/Urho3D/Physics/CollisionShape.h
  Source/Urho3D/Physics/Constraint.h
  Source/Urho3D/Physics/RigidBody.h
  Source/Urho3D/Resource/Image.h
  Source/Urho3D/Resource/JSONValue.h
  Source/Urho3D/Resource/PListFile.h
  Source/Urho3D/Resource/Resource.h
  Source/Urho3D/Resource/ResourceCache.h
  Source/Urho3D/Scene/AnimationDefs.h
  Source/Urho3D/Scene/Component.h
  Source/Urho3D/Scene/LogicComponent.h
  Source/Urho3D/Scene/Node.h
  Source/Urho3D/Scene/Scene.h
  Source/Urho3D/Scene/SmoothedTransform.h
  Source/Urho3D/Scene/ValueAnimation.h
  Source/Urho3D/UI/Cursor.h
  Source/Urho3D/UI/Font.h
  Source/Urho3D/UI/ListView.h
  Source/Urho3D/UI/Text.h
  Source/Urho3D/UI/UI.h
  Source/Urho3D/UI/UIElement.h
  Source/Urho3D/UI/Window.h
  Source/Urho3D/Urho2D/AnimatedSprite2D.h
  Source/Urho3D/Urho2D/ParticleEffect2D.h
  Source/Urho3D/Urho2D/RigidBody2D.h
  Source/Urho3D/Urho2D/SpriterData2D.h
  Source/Urho3D/Urho2D/SpriterInstance2D.h
  Source/Urho3D/Urho2D/TileMapDefs2D.h
Labels: documentation
